add_newline = false

format = """
$os\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$c\
$cmake\
$deno\
$dotnet\
$elm\
$golang\
$haskell\
$helm\
$java\
$kotlin\
$lua\
$nodejs\
$perl\
$php\
$raku\
$rlang\
$ruby\
$rust\
$terraform\
$vagrant\
$zig\
$buf\
$memory_usage\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
${custom.user_root}\
${custom.user_brad}\
${custom.user_blhotsky}\
[@](bold black)\
${custom.host_macos}\
${custom.host_linux}\
$aws\
$azure\
$jobs\
$battery\
$time\
$status\
$container\
$character"""

[custom.user_root]
when = ''' test $USER = "root" '''
command = 'whoami'
format = '''[$output](bold red)'''

[custom.user_brad]
when = ''' test $USER = "brad" '''
command = 'whoami'
format = '''[$output](bold green)'''

[custom.user_blhotsky]
when = ''' [[ "$USER" =~ "b*lhotsky" ]] '''
command = 'whoami'
format = '''[$output](bold cyan)'''

[custom.host_macos]
command = 'hostname -s'
format = '[$output](fg:blue)'
when = 'true'
os = 'macos'

[custom.host_linux]
command = 'hostname -s'
format = '[$output](fg:red)'
when = 'true'
os = 'linux'

[time]
disabled = false
format = '[ $time ]($style)'

[username]
disabled = true

[hostname]
disabled = true
