add_newline = false

format = """
[](color_blue)\
$os\
$directory\
[](fg:color_blue bg:git_color)\
$git_branch\
$git_state\
$git_metrics\
[](fg:git_color bg:color_purple)\
$git_commit\
[](fg:color_purple bg:color_red)\
$git_status\
[](fg:color_red bg:color_orange)\
$kubernetes\
[ ](fg:color_orange)\
$docker_context\
$memory_usage\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$time\
${custom.user_root}\
${custom.user_brad}\
${custom.user_blhotsky}\
$hostname\
$jobs\
$battery\
$status\
$container\
$character"""

palette = "gruvbox_dark"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
git_color = '#d79921'

[os]
style = "bg:color_blue"

[kubernetes]
disabled = false
format = "[$symbol$context(:$namespace)]($style)"
style = "bg:color_orange"

[[kubernetes.contexts]]
symbol = "󰡨 "
context_pattern = 'docker-desktop'
context_alias = ''

[[kubernetes.contexts]]
symbol = "󰵮 "
context_pattern = '.*-dev-((\w+)-?){1,2}.*'
context_alias = '$1'

[[kubernetes.contexts]]
symbol = "󰔍 "
context_pattern = '.*-sta?ge?-((\w+)-?){1,2}.*'
context_alias = '$1'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold color_fg0 bg:color_blue'
read_only_style = 'bg:color_blue'

[git_branch]
style = "bold color_fg0 bg:git_color"
symbol = " "
format = "([ $symbol$branch(:$remote_branch)]($style))"

[git_commit]
format = '([ $hash$tag]($style))'
only_detached = false
style = "bg:color_purple"

[git_metrics]
added_style = "bg:git_color"
deleted_style = "bg:git_color"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bold black bg:git_color"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bg:color_red"

[custom.user_root]
when = ''' test $USER = "root" '''
command = 'whoami'
format = '''[$output](bold color_red)'''

[custom.user_brad]
when = ''' test $USER = "brad" '''
command = 'whoami'
format = '''[$output](bold color_aqua)'''

[custom.user_blhotsky]
when = ''' [[ "$USER" =~ "b*lhotsky" ]] '''
command = 'whoami'
format = '''[$output](bold color_blue)'''

[hostname]
ssh_only = true
format = '[@](fg:bold black)[$hostname](color_blue)'

[time]
disabled = false
style = "color_yellow"
format = '[$time]($style) '
time_format = '%H:%M'

[character]
success_symbol = "[ ❯](bold color_aqua)"
error_symbol = "[ ❯](bold color_red)"

[shlvl]
disabled = true

[username]
disabled = true
