add_newline = false

format = """
[](color_blue)\
$os\
$kubernetes\
$directory\
[ ](color_blue bg:git_color)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[ ](fg:color_yellow)\
$docker_context\
$c\
$cmake\
$deno\
$golang\
$helm\
$kotlin\
$lua\
$nodejs\
$perl\
$rlang\
$ruby\
$rust\
$terraform\
$vagrant\
$zig\
$memory_usage\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
${custom.user_root}\
${custom.user_brad}\
${custom.user_blhotsky}\
$hostname\
$aws\
$azure\
$jobs\
$battery\
$time\
$status\
$container\
$character"""

palette = "gruvbox_dark"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
git_color = '#d79921'

[os]
style = "bg:color_blue"

[kubernetes]
style = "bg:color_blue"

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold color_fg0 bg:color_blue'
read_only_style = 'bg:color_blue'

[git_branch]
style = "bold color_fg0 bg:git_color"
format = "[$symbol$branch(:$remote_branch)]($style)[](color_yellow bg:color_red)"

[git_commit]
format = '[\($hash$tag\)]($style)'
style = "bg:git_color"

[git_metrics]
added_style = "bg:git_color"
deleted_style = "bg:git_color"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bold black bg:git_color"

[git_status]
format = '([$all_status$ahead_behind]($style)[](color_red bg:color_yellow))'
style = "bg:color_red"

[custom.user_root]
when = ''' test $USER = "root" '''
command = 'whoami'
format = '''[$output](bold color_red)'''

[custom.user_brad]
when = ''' test $USER = "brad" '''
command = 'whoami'
format = '''[$output](bold color_aqua)'''

[custom.user_blhotsky]
when = ''' [[ "$USER" =~ "b*lhotsky" ]] '''
command = 'whoami'
format = '''[$output](bold color_blue)'''

[hostname]
ssh_only = true
format = '[@](fg:bold black)[$hostname](color_blue)'

[time]
disabled = false
style = "color_yellow"
format = '[ $time ]($style)'
time_format = '%H:%M'

[character]
success_symbol = "[❯](bold color_aqua)"
error_symbol = "[❯](bold color_red)"

[shlvl]
disabled = true

[username]
disabled = true
