#!/bin/sh
GIT_ROOT=$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)
HOOK_NAME=$(basename $0)
LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"
script_dir="$(cd "$(dirname $0)/../scripts";pwd)"


# Run Repository Hooks
if [ -e "$LOCAL_HOOK" ]; then
    (($DEBUG)) && echo "Running local hooks: $LOCAL_HOOK"
    "$LOCAL_HOOK"
fi

# Check for global hooks
hook_scripts="$script_dir/$HOOK_NAME"
(($DEBUG)) && echo "Scanning global hooks in $hook_scripts"
if [ -d "$hook_scripts" ]; then
    for hook in $hook_scripts/*; do
        if [ -x "$hook" ]; then
            (($DEBUG)) && echo "Running $hook"
            "$hook"
        fi
    done
fi
